# Common Options
# 一般选项
[common]
# URL for the SQLite database. If empty, it will use the environment variable 'DATABASE_URL'.
# SQLite 数据库的 URL。如果为空，将使用环境变量 'DATABASE_URL'。
database_url = "sqlite://db/wmonitor.db"

# Discord bot token. If empty, it will use the environment variable 'DISCORD_BOT'.
# Discord 机器人令牌。如果为空，将使用环境变量 'DISCORD_BOT'。
discord_token = ""


# Network Options
# 网络选项
[network]
# Max capacity of cache images. 
# 图片缓存的最大容量。
image_cache_capacity = 64
# Time in minutes to cache images requested from wplace.live. 
# 从 wplace.live 请求到的图片的缓存时间（分钟）。
# Higher values mean faster checking, fewer network requests, but less timely updates.
# 数值越大，检查速度越快，网络请求次数越少，但是检查的准时性越差。
image_cache_life_min = 2
# Delay in seconds between requests to avoid being blocked by Cloudflare.
# 请求之间的延迟时间（秒），以避免被 Cloudflare 阻止。
sleep_between_requests_sec = 5


# Check Options
# 检查选项
[check]
# Minimum interval in minutes for checking each fief.
# 检查每个封地的最小间隔时间（分钟）。
minimum_interval_min = 5
# Default interval in minutes for checking each fief.
# 检查每个封地的默认间隔时间（分钟）。
default_interval_min = 15


# Notification Options
# 通知选项
[notification]
# Enable sending notifications.
# 启用发送通知。
enabled = true

# The Discord channel where the bot will send notifications.
# 机器人将发送通知的 Discord 频道。
discord_channel = ""

# Event types that will trigger a notification.
# 将触发通知的事件类型。
# Available values and their descriptions:
# 可用值及其描述：
# 'DIFF_FOUND': A change or difference has been detected.
# 'DIFF_FOUND': 检测到变更或差异。
# 'APP_START': The application has started.
# 'APP_START': 应用程序已启动。
# 'APP_ERROR': An application-level error has occurred.
# 'APP_ERROR': 发生应用程序级错误。
# 'APP_STOP': The application has stopped.
# 'APP_STOP': 应用程序已停止。
# 'SKIP_CHECK_BEGIN': The check for a specific fief has been temporarily skipped.
# 'SKIP_CHECK_BEGIN': 对特定封地的检查已暂时跳过。
# 'SKIP_CHECK_END': The temporary skipping of checks has ended.
# 'SKIP_CHECK_END': 检查的临时跳过已结束。
# 'CHECK_ERROR': An error occurred during the check process.
# 'CHECK_ERROR': 检查过程中发生错误。
event_filter = [
    'APP_START',
    'APP_ERROR',
    'APP_STOP',
    'SKIP_CHECK_BEGIN',
    'SKIP_CHECK_END',
    'DIFF_FOUND',
    'CHECK_ERROR',
]


# Visualization Options
# 可视化选项
[visualization]
# Opacity percentage for difference image
# 差异图像的不透明度（百分比）
diff_img_opacity_pct = 85

# Normal pixel color in RGB format
# 正常像素的RGB颜色
normal_color = 0xFFFFFF

# Abnormal pixel color in RGB format
# 异常像素的RGB颜色
abnormal_color = 0xFF0000

# Unmasked area color in RGB format
# 未遮罩区域的RGB颜色
unmasked_color = 0x000000

# Minimum width in pixels for the visualization result
# 可视化结果的最小像素宽度
minimum_width = 80

# Minimum height in pixels for the visualization result
# 可视化结果的最小像素高度
minimum_height = 60

# Horizontal margin in pixels for the visualization result
# 可视化结果的水平边缘大小
horizontal_margin = 8

# Vertical margin in pixels for the visualization result
# 可视化结果的垂直边缘大小
vertical_margin = 6